services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      target: dev
    ports:
      - 80:80
    networks:
      - backend
    volumes:
      - ./frontend/:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/:/app

  db:
    image: "postgres:17-alpine"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - db-store:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  db-store:

networks:
  backend:
    driver: bridge
