services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - frontend
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    expose:
      - 8080
    networks:
      - frontend
      - backend
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "postgres:17-alpine"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - db-store:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 5s

volumes:
  db-store:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
