services:
  frontend:
    build:
      target: dev
    volumes:
      - .:/workspaces/mika:cached
      - /workspaces/mika/frontend/node_modules

  backend:
    build:
      target: dev
    environment:
      - GIN_MODE=debug
      - ENVIRONMENT=dev
    volumes:
      - .:/workspaces/mika:cached
